title: Ahmed Bouchefra
description: Web developer and technical writer

url: https://www.ahmedbouchefra.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: techiediaries
  twitter: ahmedbouchefra
  facebook: ahmed.bouchefra
  email: techiediaries9@gmail.com

google_analytics: "UA-74071120-3"
